[project]
name = "myproj"
version = "0.0.0"
dependencies = [
  "clearml==2.0.2",
  "draccus==0.10.0"
  # add your deps here
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

